[package]
name = "pwgen"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5" }
rand_chacha = { version = "0.3.1" }
clap = { version = "4.4.18", features = ["derive"] }
